name: backend-deployment

on:
  push:
    branches:
      - main

jobs:
  BUILD:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t sainathdev7/codeveritus-backend:latest .

      - name: Push to Docker Hub
        run: docker push sainathdev7/codeveritus-backend:latest

  DEPLOY:
    needs: BUILD
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull sainathdev7/codeveritus-backend:latest

      - name: Delete old container
        run: docker rm -f backend-container || true

      - name: Run container (HTTPS enabled)
        run: |
          docker run -d \
            --name backend-container \
            --network=codeveritus-network \
            -p 4000:4000 \
            -e MONGO_URI="${{ secrets.MONGO_URI }}" \
            -e CORE_API="${{ secrets.CORE_API }}" \
            -e SALTROUNDS="${{ secrets.SALTROUNDS }}" \
            -e JWT_SECRET_TOKEN="${{ secrets.JWT_SECRET_TOKEN }}" \
            sainathdev7/codeveritus-backend:latest
